CREATE DATABASE IF NOT EXISTS desafioo;

CREATE TABLE desafioo.client(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome_fantasia VARCHAR(200) NOT NULL
);

CREATE TABLE desafioo.user(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(200) NOT NULL
);